"""Add agency role and profile fields

Revision ID: 062dcdd284a0
Revises: cc0eba2cc89a
Create Date: 2026-10-09 17:43:19.619756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '062dcdd284a0'
down_revision: Union[str, Sequence[str], None] = 'cc0eba2cc89a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hiring_requests') as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_hiring_requests_profile_id', 'provider_profiles', ['profile_id'], ['id'])

    with op.batch_alter_table('provider_profiles') as batch_op:
        batch_op.add_column(sa.Column('agency_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(), nullable=True))
        batch_op.alter_column('user_id', existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_foreign_key('fk_provider_profiles_agency_id', 'users', ['agency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_profiles') as batch_op:
        batch_op.drop_constraint('fk_provider_profiles_agency_id', type_='foreignkey')
        batch_op.alter_column('user_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column('full_name')
        batch_op.drop_column('agency_id')

    with op.batch_alter_table('hiring_requests') as batch_op:
        batch_op.drop_constraint('fk_hiring_requests_profile_id', type_='foreignkey')
        batch_op.drop_column('profile_id')
    # ### end Alembic commands ###
