"""Add profile models

Revision ID: 2b64b1a881b4
Revises: 6d69c0bc0914
Create Date: 2026-10-07 18:09:52.799692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b64b1a881b4'
down_revision: Union[str, Sequence[str], None] = '6d69c0bc0914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_customer_profiles_id'), 'customer_profiles', ['id'], unique=False)
    op.create_table('provider_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('skills', sa.String(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('expected_wage', sa.Float(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_provider_profiles_id'), 'provider_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_provider_profiles_industry'), 'provider_profiles', ['industry'], unique=False)
    op.create_index(op.f('ix_provider_profiles_location'), 'provider_profiles', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_profiles_location'), table_name='provider_profiles')
    op.drop_index(op.f('ix_provider_profiles_industry'), table_name='provider_profiles')
    op.drop_index(op.f('ix_provider_profiles_id'), table_name='provider_profiles')
    op.drop_table('provider_profiles')
    op.drop_index(op.f('ix_customer_profiles_id'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    # ### end Alembic commands ###
