"""Add customer image_url

Revision ID: 347bedd04a7e
Revises: b0bae7bda397
Create Date: 2026-10-08 20:31:20.750057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347bedd04a7e'
down_revision: Union[str, Sequence[str], None] = 'b0bae7bda397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_profiles', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_profiles', 'image_url')
    # ### end Alembic commands ###
