"""Add image_url to provider

Revision ID: 967a758ad448
Revises: f0b6049ff0e7
Create Date: 2026-10-07 20:31:00.341949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967a758ad448'
down_revision: Union[str, Sequence[str], None] = 'f0b6049ff0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_profiles', 'image_url')
    # ### end Alembic commands ###
