"""Add portfolio_urls

Revision ID: b0bae7bda397
Revises: bf104e464aa5
Create Date: 2026-10-08 20:21:41.491334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0bae7bda397'
down_revision: Union[str, Sequence[str], None] = 'bf104e464aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('portfolio_urls', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_profiles', 'portfolio_urls')
    # ### end Alembic commands ###
